[tool.pylint]
max-line-length = 200
ignored-modules = ["alembic"]

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 200

[tool.black]
line-length = 200

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = "--import-mode=importlib"

[tool.pytest_env]
PROJECT_NAME = "test-fastapi"
REPOSITORY_URL = "https://some-repo.git"
TRUSTED_OP_LIST = '["https://aai-dev.egi.eu/auth/realms/egi"]'
ADMIN_SECRET = "6de44315b565ea73f778282d"
SMTP_HOST = "smtp_server"
SMTP_PORT = "587"
