[tool.pylint]
max-line-length = 200
ignored-modules = ["alembic"]

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 200

[tool.black]
line-length = 200

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = "--import-mode=importlib"
