""""standard"

Revision ID: e4cb3fa0953e
Revises: 04deff42e0f0
Create Date: 2023-10-30 09:30:21.677296

"""
# pylint: disable=missing-function-docstring
# pylint: disable=invalid-name
import sqlalchemy as sa

import app.database
from alembic import op


# revision identifiers, used by Alembic.
revision = "e4cb3fa0953e"
down_revision = "04deff42e0f0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("template", sa.Column("feedback", sa.String(), nullable=False, server_default='lorem ipsum',))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("template", "feedback")
    # ### end Alembic commands ###
