services:
  backend:
    image: backend:development
    restart: no
    depends_on:
      - database
    ports:
      - 80:8000
    build:
      tags: [backend:development]
      target: development

  database:
    image: postgres:15
    restart: no
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: no
    depends_on:
      - database
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    env_file:
      - .env
    ports:
      - 5050:80

volumes:
  pg-db-data:
