services:
  backend:
    image: backend:development
    restart: no
    depends_on:
      - database
    volumes:
      - .:/app
    ports:
      - 8000:8000
      - 5678:5678
    build:
      tags: [backend:development]
      target: development

  database:
    image: postgres:15
    restart: no
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: no
    depends_on:
      - database
    volumes:
      - app-pgadmin:/var/lib/pgadmin
    env_file:
      - .env
    ports:
      - 5050:80

volumes:
  app-pgadmin:
