services:
  backend:
    restart: always
    env_file: [.env]
    ports:
      - 80:8000
    build:
      tags: [backend]
      target: production

  database:
    restart: always
    env_file: [.env]
    volumes:
      - ./scripts/setup_migration.sql:/docker-entrypoint-initdb.d/setup_migration.sql
      - app-db-data:/var/lib/postgresql/data/pgdata

  smtp_server:
    image: boky/postfix:v3.6.1-alpine
    restart: always
    ports:
      - 587:587

volumes:
  app-db-data:
