services:
  backend:
    restart: always
    env_file: [.env]
    ports:
      - 80:8000
    build:
      tags: [backend]
      target: production

  database:
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Undefined POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER:?Undefined POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB:-application}
    volumes:
      - ./scripts/setup_migration.sql:/docker-entrypoint-initdb.d/setup_migration.sql
      - app-db-data:/var/lib/postgresql/data/pgdata

  smtp_server:
    image: boky/postfix:v3.6.1-alpine
    restart: always
    ports:
      - 587:587

volumes:
  app-db-data:
