services:
  backend:
    image: backend:testing
    restart: "no"
    build:
      tags: [backend:testing]
      target: testing
    environment:
      POSTGRES_HOST: database

  database:
    restart: "no"
    volumes:
      - ./scripts/setup_migration.sql:/docker-entrypoint-initdb.d/0-setup_migration.sql
      - ./scripts/setup_sandbox.sql:/docker-entrypoint-initdb.d/1-setup_sandbox.sql
    environment:
      POSTGRES_PASSWORD: db_password
      POSTGRES_USER: db_user
      POSTGRES_DB: db_name
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"

  smtp_server:
    restart: "no"
